
get_sfx(soundin)
	. = ..()
	if(.)
		return .
	if(istext(soundin))
		switch(soundin)
			if("dog")
				soundin = pickweight(list('aquila/sound/voice/speech/dog1.ogg' = 49, 'aquila/sound/voice/speech/dogarf.ogg' = 1))
			if("cat")
				soundin = pick('aquila/sound/voice/speech/cat1.ogg')
			if("monkey")
				soundin = pick('aquila/sound/voice/speech/monkey1.ogg', 'aquila/sound/voice/speech/monkey2.ogg')
			if("parrot")
				soundin = pick('aquila/sound/voice/speech/parrot1.ogg', 'aquila/sound/voice/speech/parrot2.ogg', 'aquila/sound/voice/speech/parrot3.ogg')
			if("slime")
				soundin = pick('aquila/sound/voice/speech/slime1.ogg')
			if("humanmale")
				soundin = pick('aquila/sound/voice/speech/humanmale1.ogg', 'aquila/sound/voice/speech/humanmale2.ogg', 'aquila/sound/voice/speech/humanmale3.ogg', 'aquila/sound/voice/speech/humanmale4.ogg', 'aquila/sound/voice/speech/humanmale5.ogg')
			if("humanfemale")
				soundin = pick('aquila/sound/voice/speech/humanfemale1.ogg', 'aquila/sound/voice/speech/humanfemale2.ogg', 'aquila/sound/voice/speech/humanfemale3.ogg', 'aquila/sound/voice/speech/humanfemale4.ogg')
			if("humanplural")
				soundin = pick('aquila/sound/voice/speech/humanplural.ogg')
			if("lizard")
				soundin = pick('aquila/sound/voice/speech/lizard1.ogg', 'aquila/sound/voice/speech/lizard2.ogg', 'aquila/sound/voice/speech/lizard3.ogg')
			if("moth")
				soundin = pick('aquila/sound/voice/speech/moth1.ogg', 'aquila/sound/voice/speech/moth2.ogg', 'aquila/sound/voice/speech/moth3.ogg')
			if("chatter")
				soundin = pick('aquila/sound/voice/speech/chatter1.ogg', 'aquila/sound/voice/speech/chatter2.ogg')
			if("synthetic")
				soundin = pick('aquila/sound/voice/speech/synthetic1.ogg', 'aquila/sound/voice/speech/synthetic2.ogg', 'aquila/sound/voice/speech/synthetic3.ogg')
			if("insect")
				soundin = pick('aquila/sound/voice/speech/insect1.ogg', 'aquila/sound/voice/speech/insect2.ogg', 'aquila/sound/voice/speech/insect3.ogg')
			if("drone")
				soundin = pick('aquila/sound/voice/speech/drone1.ogg', 'aquila/sound/voice/speech/drone2.ogg', 'aquila/sound/voice/speech/drone3.ogg')
			if("plasma")
				soundin = pick('aquila/sound/voice/speech/plasma1.ogg', 'aquila/sound/voice/speech/plasma2.ogg', 'aquila/sound/voice/speech/plasma3.ogg')
			if("pod")
				soundin = pick('aquila/sound/voice/speech/pod1.ogg')
			if("shadow")
				soundin = pick('aquila/sound/voice/speech/shadow1.ogg', 'aquila/sound/voice/speech/shadow2.ogg', 'aquila/sound/voice/speech/shadow3.ogg')
			if("squid")
				soundin = pick('aquila/sound/voice/speech/squid1.ogg', 'aquila/sound/voice/speech/squid2.ogg', 'aquila/sound/voice/speech/squid3.ogg')
			if("zombie")
				soundin = pick('aquila/sound/voice/speech/zombie1.ogg', 'aquila/sound/voice/speech/zombie2.ogg', 'aquila/sound/voice/speech/zombie3.ogg')
			//if("egg")
			//	soundin = pick('sound/voice/eggperson/egg_scream.ogg')
			if("skeleton")
				soundin = pick('aquila/sound/voice/speech/skeleton1.ogg', 'aquila/sound/voice/speech/skeleton2.ogg', 'aquila/sound/voice/speech/skeleton3.ogg')
			if("golem")
				soundin = pick('aquila/sound/voice/speech/golem1.ogg')
			if("felinid")	// Why awe we stiww hewe?!! Just t-to suffew?!?1 *sees buldge*
				soundin = pick('aquila/sound/voice/speech/felinid1.ogg', 'aquila/sound/voice/speech/felinid2.ogg', 'aquila/sound/voice/speech/felinid3.ogg', 'aquila/sound/voice/speech/felinid4.ogg')
